[package]
name = "slow_align"
version = "0.1.0"
authors = ["Vilém Zouhar <vilem.zouhar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
clap = "3.0.0-beta.2"